### ISSUE TITLE
Instalação da versão 1.2.3

### ISSUE THREAD

**Issue by rafa-acioly** [ModulosFK/fkcorreiosg2#1]
Estou com uma instalação do prestashop na versão 1.6.1.2 e após o `upload` do módulo recebo a mensagem que o mesmo foi importado com sucesso, porém ele não aparece na lista de módulos e isso impossibilita que eu acesse as configurações.

versão do php: 5.6
Disco: 60GB
RAM: 1GB

(Também testado na versão 1.6.1.17 do prestashop)

**Comment by marcelphilippe** [comment]
Extraia direto do zip para a pasta módulos e remova o " - " do nome do módulo.
Antes: fkcorreiosg2-master
Depois: fkcorreiosg2master

**Comment by eloimarquessilva** [comment]
Exatamente, o problema está no nome da pasta ao ser extraída no servidor. O melhor caminho para upar o módulo é extraí-lo no seu computador, certificar-se que o nome da pasta
 é "fkcorreiosg2" (apenas isso), subir esta pasta para seu servidor via FTP e realizar a instalação a partir da interface da PrestaShop.


![tela-1](https://user-images.githubusercontent.com/11034410/34836510-3e67fdf6-f6df-11e7-9119-e5fb87cec8be.png)
